services:
  weaviate:
    image: semitechnologies/weaviate:1.27.6
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - "8080:8080"
      - "50051:50051" # gRPC
    environment:
      QUERY_DEFAULTS_LIMIT: "20"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      ENABLE_MODULES: "text2vec-openai" 
      OPENAI_APIKEY: "${OPENAI_API_KEY}"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      LOG_LEVEL: "debug"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - ./data:/var/lib/weaviate
